### ISSUE TITLE
Code is not licensed

### ISSUE THREAD

**Issue by timlnx** [timlnx/py-prtstat#3]
I hate unlicensed projects. We need to include a license. Since I haven't written the majority of the code I'll leave the decision to the other committers. However, I would like to suggest my license of choice, the bsd v2 license which you can see an example of on my pad-xmpp project.

https://github.com/tbielawa/PAD-XMPP/blob/master/src/HEADER

**Comment by kelcecil** [comment]
Works for me.

**Comment by abutcher** [comment]
I support this,

**Comment by rhussmann** [comment]
+1

**Comment by timlnx** [comment]
it's decided

**Comment by timlnx** [comment]
This issue is resolved in a693860c27730ba1b6f79cddc1488f725c083613
