### ISSUE TITLE
Allow for input of test data

### ISSUE THREAD

**Issue by rhussmann** [timlnx/py-prtstat#5]
After seeing an outage today, I suggest we start to implement a way to input Tweets from a file in addition to directly from Twitter. This will allow us to control the content that goes into the system. In preparation for something like this, I've created a 'data' folder with an 'up' and 'down' subfolder, each containing representative data when the PRT is either functional ('up'), or broken or functioning sporadically ('down').

What I'm not sure of is the best way to capture the data. We certainly can't capture every tweet on Twitter within a certain timeframe, so we'll have to use some sort of filters. However, I'm sure we'll want to experiment with the filters we use with Twitter (geocode, location, timeframe). With that in mind, if you do capture data, please list the search filter used when querying Twitter so we can record all the details.

I imagine that the filters we're using right now will be relatively standard (geocode, near location), although we might want to tweak the 'near' field.

**Comment by timlnx** [comment]
I'm willing to donate some cpu cycles on my slice host to collect data with. My first thoughts are a periodic cron job which logs the weather data at the moment taken, and the "status" of the PRT, as per http://prt.wvu.edu.

I think I'll follow it up with a php script that responds in json when you GET it. This way the data is saved, updated, and able to be queried.

**Comment by abutcher** [comment]
I've implemented a cronjob/restful push to my site prtdata.afrolegs.com to satisfy this requirement.
